### ISSUE TITLE
No response when city is not found

### ISSUE THREAD

**Issue by farreltobias** [DaviLhlapakRosa/weather-app#1]
A 504 Gateway Error status code is returned when it supposed to be a 404 status code (if this is a library feature then disconsider this).

App is supposed to inform client that response weather was not found and/or to search a new city. But request keeps loading

<p align="center">
  <img src="https://user-images.githubusercontent.com/54959451/108632712-1e07d400-744f-11eb-9fbc-1189113df9ac.png" width="75%">
</p>

**Comment by DaviLhlapak** [comment]
Thank you, i added a new message error when city is not found or api not response.
