### ISSUE TITLE
Design fixes in mobile

### ISSUE THREAD

**Issue by farreltobias** [DaviLhlapakRosa/weather-app#2]
Device: Motorola Moto Z Play

A small design fix when city has two lines

<p align="center">
  <img src="https://user-images.githubusercontent.com/54959451/108632516-26134400-744e-11eb-8be4-984965bfd575.png" width="50%" />
</p>

**Comment by DaviLhlapakRosa** [comment]
Fixed design when city has two lines and updated mobile style.

**Comment by DaviLhlapak** [comment]
Fixed design when city has two lines and updated mobile style.
